# Generated by Django 3.2.3 on 2021-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system_app', '0002_studentdetail_proctor_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='position_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
